[versions]
agp = "8.11.0"
kotlin = "2.2.0"
android-tools-desugar = "2.1.5"

koin-android = "4.1.0"

kotlinx-coroutines = "1.10.2"

androidx-core-ktx = "1.16.0"
androidx-core-splashscreen = "1.2.0-rc01"
androidx-activity-compose = "1.10.1"
androidx-fragment = "1.8.8"
androidx-appcompat = "1.7.1"
androidx-lifecycle = "2.9.1"
androidx-window = "1.4.0"
androidx-datastore-preferences = "1.1.7"

compose-bom = "2025.06.01"

process-phoenix = "3.0.0"
xlog = "1.11.1"

#MJPEG
ktor = "3.2.1"

#PlayStore-WebRTC
play-services-tasks = "18.3.0"
play-integrity = "1.4.0"
socket = "2.1.2"
okio = "3.15.0"
okhttp = "5.0.0"

#PlayStore-App
play-app-update = "2.1.0"
play-app-review = "2.0.2"
play-services-ads = "24.4.0"
webkit = "1.14.0"
firebase-analytics = "22.5.0"
firebase-crashlytics = "19.4.4"
google-services = "4.4.3"
crashlytics-gradle = "3.0.4"

[libraries]
android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-tools-desugar" }
kotlinStdlibJdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-android" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore-preferences" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-window = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite"  }
androidx-compose-material3-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout"  }
androidx-compose-material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation"  }

processPhoenix = { module = "com.jakewharton:process-phoenix", version.ref = "process-phoenix" }
xlog = { module = "com.elvishew:xlog", version.ref = "xlog" }

#MJPEG
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-caching-headers = { module = "io.ktor:ktor-server-caching-headers", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-forwarded-header = { module = "io.ktor:ktor-server-forwarded-header", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }

#RTSP
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
ktor-network-tls = { module = "io.ktor:ktor-network-tls", version.ref = "ktor" }

#PlayStore-WebRTC
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "play-services-tasks" }
play-integrity = { module = "com.google.android.play:integrity", version.ref = "play-integrity" }
socket = { module = "io.socket:socket.io-client", version.ref = "socket" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

#PlayStore-App
play-app-update = { module = "com.google.android.play:app-update-ktx", version.ref = "play-app-update" }
play-app-review = { module = "com.google.android.play:review-ktx", version.ref = "play-app-review" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "play-services-ads" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk", version.ref = "firebase-crashlytics" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics-gradle" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

#PlayStore
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics-gradle" }