[versions]
agp = "8.4.1"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.21"
android-tools-r8 = "8.3.37"
android-tools-desugar = "2.0.4"

koin-android-compose = "3.5.6"
koin-ksp = "1.3.1"

kotlinx-coroutines = "1.8.1"

androidx-core-ktx = "1.13.1"
androidx-core-splashscreen = "1.1.0-rc01"
androidx-activity-compose = "1.9.0"
androidx-appcompat = "1.7.0-rc01"
androidx-lifecycle = "2.8.0"
androidx-window = "1.3.0-rc01"
androidx-datastore-preferences = "1.1.1"

compose-bom = "2024.05.00"
material3-adaptive-navigation-suite = "1.0.0-alpha07"
material3-adaptive = "1.0.0-beta01"

process-phoenix = "3.0.0"
xlog = "1.11.0"

#MJPEG
ktor = "2.3.11"

#PlayStore-WebRTC
play-services-tasks = "18.1.0"
play-integrity = "1.3.0"
webrtc = "1.1.2"
socket = "2.1.0"
okhttp = "4.12.0"

#PlayStore-App
play-app-update = "2.1.0"
play-services-ads = "23.1.0"
webkit = "1.11.0"
firebase-analytics = "22.0.0"
firebase-crashlytics = "19.0.0"
google-services = "4.4.1"
crashlytics-gradle = "3.0.1"

[libraries]
android-tools-r8 = { module = "com.android.tools:r8", version.ref = "android-tools-r8" }
android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-tools-desugar" }

koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-android-compose" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-ksp" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-ksp" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore-preferences" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-window = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3-adaptive-navigation-suite" }
androidx-compose-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }
androidx-compose-material3-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "material3-adaptive" }
androidx-compose-material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "material3-adaptive" }

androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

processPhoenix = { module = "com.jakewharton:process-phoenix", version.ref = "process-phoenix" }
xlog = { module = "com.elvishew:xlog", version.ref = "xlog" }

#MJPEG
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-caching-headers = { module = "io.ktor:ktor-server-caching-headers", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-forwarded-header = { module = "io.ktor:ktor-server-forwarded-header", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }

#PlayStore-WebRTC
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "play-services-tasks" }
play-integrity = { module = "com.google.android.play:integrity", version.ref = "play-integrity" }
webrtc = { module = "io.getstream:stream-webrtc-android-ktx", version.ref = "webrtc" }
socket = { module = "io.socket:socket.io-client", version.ref = "socket" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

#PlayStore-App
play-app-update = { module = "com.google.android.play:app-update-ktx", version.ref = "play-app-update" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "play-services-ads" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics-gradle" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

#PlayStore
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics-gradle" }